# Generated by Django 5.0.6 on 2024-06-26 20:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время')),
                ('action', models.CharField(max_length=250, verbose_name='действие')),
                ('is_enjoyable', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('periodicity', models.CharField(choices=[('DAILY', 'ежедневно'), ('WEEKLY', 'еженедельно')], default='DAILY', max_length=20, verbose_name='периодичность')),
                ('reward', models.CharField(blank=True, max_length=250, null=True, verbose_name='вознаграждение')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='продолжительность выполнения')),
                ('is_public', models.BooleanField(default=True, verbose_name='признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
